#pragma once

typedef enum {
	CAMERA_FRONT, CAMERA_BACK, CAMERA_RIGHT, CAMERA_LEFT, CAMERA_UP, CAMERA_DOWN
} USER_ACTION_CAMERA;

typedef enum {
	ROTATED_AROUND_X, ROTATED_AROUND_Y, ROTATED_AROUND_Z
}ROTATION_TYPE;

typedef enum {
	ROBOT_MOVE_FRONT, ROBOT_MOVE_BACK
}ROBOT_MOVE_DIRECTION;
